// listActionTypes.js
export const FETCH_LIST_REQUEST = "FETCH_LIST_REQUEST";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE";

export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const ITEM_ACTION_FAILURE = "ITEM_ACTION_FAILURE";
export const ADD_LIST_ITEM = "ADD_LIST_ITEM";