export const EDIT_STUDENT_REQUEST = "EDIT_STUDENT_REQUEST";
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";

export const EMAIL_VERIFICATION_REQUEST = "EMAIL_VERIFICATION_REQUEST";
export const EMAIL_VERIFICATION_ERROR = "EMAIL_VERIFICATION_ERROR";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const RESET_LINK_REQUEST = "RESET_LINK_REQUEST";
export const RESET_LINK_ERROR = "RESET_LINK_ERROR";
export const RESET_LINK_SUCCESS = "RESET_LINK_SUCCESS";

export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST";
export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";

export const GOOGLE_LOGIN_STUDENT_REQUEST = "GOOGLE_LOGIN_STUDENT_REQUEST";
export const GOOGLE_LOGIN_STUDENT_ERROR = "GOOGLE_LOGIN_STUDENT_ERROR";
export const GOOGLE_LOGIN_STUDENT_SUCCESS = "GOOGLE_LOGIN_STUDENT_SUCCESS";

export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_ERROR = "REGISTER_STUDENT_ERROR";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";

export const GOOGLE_REGISTER_STUDENT_REQUEST =
  "GOOGLE_REGISTER_STUDENT_REQUEST";
export const GOOGLE_REGISTER_STUDENT_ERROR = "GOOGLE_REGISTER_STUDENT_ERROR";
export const GOOGLE_REGISTER_STUDENT_SUCCESS =
  "GOOGLE_REGISTER_STUDENT_SUCCESS";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CHECK_AUTH = "CHECK_AUTH";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
