export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CHECK_AUTH = "CHECK_AUTH";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
